const { withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * Config plugin to fix React Native Firebase non-modular header errors
 * with Expo SDK 54+ and useFrameworks: 'static'
 * 
 * Reference: https://github.com/invertase/react-native-firebase/issues/8657
 * 
 * This plugin uses withDangerousMod to directly modify the Podfile
 * after it's been generated by expo prebuild.
 */
const withFirebaseModularHeaders = (config) => {
  return withDangerousMod(config, [
    'ios',
    async (config) => {
      const podfilePath = path.join(
        config.modRequest.platformProjectRoot,
        'Podfile'
      );

      console.log('[withFirebaseModularHeaders] Looking for Podfile at:', podfilePath);

      if (!fs.existsSync(podfilePath)) {
        console.log('[withFirebaseModularHeaders] Podfile not found, skipping');
        return config;
      }

      let podfileContents = fs.readFileSync(podfilePath, 'utf-8');
      console.log('[withFirebaseModularHeaders] Podfile found, checking for existing fix...');

      // Check if fix is already applied
      if (podfileContents.includes('CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES')) {
        console.log('[withFirebaseModularHeaders] Fix already present in Podfile');
        return config;
      }

      const clangFix = `
    # Fix for React Native Firebase non-modular headers (Expo SDK 54+)
    # https://github.com/invertase/react-native-firebase/issues/8657
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build_config|
        build_config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      end
    end
`;

      // Find post_install block and insert after it
      const postInstallRegex = /post_install do \|installer\|/;
      const postInstallMatch = podfileContents.match(postInstallRegex);

      if (postInstallMatch) {
        console.log('[withFirebaseModularHeaders] Found post_install block, inserting fix...');
        const insertPosition = postInstallMatch.index + postInstallMatch[0].length;
        podfileContents = 
          podfileContents.slice(0, insertPosition) + 
          clangFix + 
          podfileContents.slice(insertPosition);
        
        fs.writeFileSync(podfilePath, podfileContents);
        console.log('[withFirebaseModularHeaders] Successfully patched Podfile!');
      } else {
        console.error('[withFirebaseModularHeaders] ERROR: Could not find post_install block in Podfile');
        console.log('[withFirebaseModularHeaders] Podfile contents start:', podfileContents.substring(0, 500));
      }

      return config;
    },
  ]);
};

module.exports = withFirebaseModularHeaders;
