import Constants from "expo-constants";

const RAW_API_BASE_URL =
  Constants.expoConfig?.extra?.apiBaseUrl ||
  process.env.EXPO_PUBLIC_VMS_API_BASE_URL || '';

// Normalize: remove trailing /api or /api/ to avoid duplicate paths
const API_BASE_URL = RAW_API_BASE_URL.replace(/\/api\/?$/, '');

const MICROSOFT_AUTH_BASE_URL =
  Constants.expoConfig?.extra?.microsoftAuthUrl ||
  process.env.EXPO_PUBLIC_MICROSOFT_AUTH_URL || '';

export const apiConfig = {
  baseUrl: API_BASE_URL,
  microsoftAuthUrl: MICROSOFT_AUTH_BASE_URL,
  timeout: 30000,
  endpoints: {
    health: "/api/health",
    healthDb: "/api/health/db",
    auth: {
      base: "/api/v1/auth",
      health: "/api/v1/auth/health",
      config: "/api/v1/auth/config",
      login: "/api/v1/auth/login",
      azureLogin: "/api/v1/auth/azure/login",
      azureCallback: "/api/v1/auth/azure/callback",
      microsoftLogin: "/auth/microsoft/login",
      microsoftCallback: "/auth/microsoft/callback",
      refresh: "/api/v1/auth/refresh",
      logout: "/api/v1/auth/logout",
      password: "/api/v1/auth/password",
      forgotPassword: "/api/v1/auth/forgot-password",
      resetPassword: "/api/v1/auth/reset-password",
      resetPasswordWithOtp: "/api/v1/auth/reset-password-with-otp",
      sendOtp: "/api/v1/auth/send-otp",
      verifyOtp: "/api/v1/auth/verify-otp",
      resendOtp: "/api/v1/auth/resend-otp",
      notificationPreferences: "/api/v1/auth/notification-preferences",
      biometric: {
        register: "/api/v1/auth/biometric/register",
        devices: "/api/v1/auth/biometric/devices",
        verify: "/api/v1/auth/biometric/verify",
        settings: "/api/v1/auth/biometric/settings",
        challenge: "/api/v1/auth/biometric/challenge",
      },
    },
    users: {
      base: "/api/v1/users",
      me: "/api/v1/users/me",
      mePhoto: "/api/v1/users/me/photo",
      onVacation: "/api/v1/users/on-vacation",
      byId: (id: string) => `/api/v1/users/${id}`,
      byRole: (role: string) => `/api/v1/users/by-role/${role}`,
      team: (managerId: string) => `/api/v1/users/${managerId}/team`,
    },
    visitors: {
      base: "/api/v1/visitors",
      check: "/api/v1/visitors/check",
      blacklisted: "/api/v1/visitors/blacklisted",
      byId: (id: string) => `/api/v1/visitors/${id}`,
      blacklist: (id: string) => `/api/v1/visitors/${id}/blacklist`,
    },
    invitations: {
      base: "/api/v1/invitations",
      today: "/api/v1/invitations/today",
      myUpcoming: "/api/v1/invitations/my-upcoming",
      byId: (id: string) => `/api/v1/invitations/${id}`,
      respond: (token: string) => `/api/v1/invitations/respond/${token}`,
      checkIn: (id: string) => `/api/v1/invitations/${id}/check-in`,
      checkOut: (id: string) => `/api/v1/invitations/${id}/check-out`,
    },
    publicInvites: {
      byToken: (token: string) => `/api/v1/invites/${token}?format=json`,
      accept: (token: string) => `/api/v1/invites/${token}/accept?format=json`,
      reject: (token: string) => `/api/v1/invites/${token}/reject?format=json`,
    },
    visits: {
      base: "/api/v1/visits",
      roomsAvailability: "/api/v1/visits/rooms/availability",
      byId: (id: string) => `/api/v1/visits/${id}`,
      approve: (id: string) => `/api/v1/visits/${id}/approve`,
      reject: (id: string) => `/api/v1/visits/${id}/reject`,
      hostApprove: (id: string) => `/api/v1/visits/${id}/host-approve`,
      hostReject: (id: string) => `/api/v1/visits/${id}/host-reject`,
      checkIn: (id: string) => `/api/v1/visits/${id}/check-in`,
      checkOut: (id: string) => `/api/v1/visits/${id}/check-out`,
    },
    requests: {
      base: "/api/v1/requests",
      myRequests: "/api/v1/requests/my-requests",
      pendingApprovals: "/api/v1/requests/pending-approvals",
      byId: (id: string) => `/api/v1/requests/${id}`,
      approve: (id: string) => `/api/v1/requests/${id}/approve`,
      reject: (id: string) => `/api/v1/requests/${id}/reject`,
    },
    approvals: {
      pending: "/api/v1/approvals/pending",
      pendingHost: "/api/v1/approvals/pending-host",
      awaitingVisitor: "/api/v1/approvals/awaiting-visitor",
      bulkApprove: "/api/v1/approvals/bulk/approve",
      bulkReject: "/api/v1/approvals/bulk/reject",
    },
    parking: {
      base: "/api/v1/parking",
      spaces: "/api/v1/parking/spaces",
      spacesAvailable: "/api/v1/parking/spaces/available",
      allocateAuto: "/api/v1/parking/allocate/auto",
      allocations: "/api/v1/parking/allocations",
      stats: "/api/v1/parking/stats",
      employees: "/api/v1/parking/employees",
      bulkAssign: "/api/v1/parking/employees/bulk-assign",
      spaceById: (id: string) => `/api/v1/parking/spaces/${id}`,
      allocateToSpace: (spaceId: string) => `/api/v1/parking/allocate/${spaceId}`,
      allocationCheckIn: (id: string) => `/api/v1/parking/allocations/${id}/check-in`,
      allocationCheckOut: (id: string) => `/api/v1/parking/allocations/${id}/check-out`,
      allocationRelease: (id: string) => `/api/v1/parking/allocations/${id}/release`,
      spots: "/api/v1/parking/spots",
      spotById: (id: string) => `/api/v1/parking/spots/${id}`,
    },
    meetingRooms: {
      base: "/api/v1/meeting-rooms",
      available: "/api/v1/meeting-rooms/available",
      bookings: "/api/v1/meeting-rooms/bookings",
      bookingsAll: "/api/v1/meeting-rooms/bookings/all",
      bookingsToday: "/api/v1/meeting-rooms/bookings/today",
      byId: (id: string) => `/api/v1/meeting-rooms/${id}`,
      bookingById: (id: string) => `/api/v1/meeting-rooms/bookings/${id}`,
    },
    buffet: {
      base: "/api/v1/buffet",
      locations: "/api/v1/buffet/locations",
      staff: "/api/v1/buffet/staff",
      staffOnDuty: "/api/v1/buffet/staff/on-duty",
      requests: "/api/v1/buffet/requests",
      requestsToday: "/api/v1/buffet/requests/today",
      requestsPending: "/api/v1/buffet/requests/pending",
      locationById: (id: string) => `/api/v1/buffet/locations/${id}`,
      staffById: (id: string) => `/api/v1/buffet/staff/${id}`,
      requestById: (id: string) => `/api/v1/buffet/requests/${id}`,
      requestHandle: (id: string) => `/api/v1/buffet/requests/${id}/handle`,
    },
    buffetStaff: {
      base: "/api/v1/buffet-staff",
      myTasks: "/api/v1/buffet-staff/my-tasks",
      taskStatus: (id: string) => `/api/v1/buffet-staff/tasks/${id}/status`,
    },
    buffetAdmin: {
      base: "/api/v1/buffet-admin",
      tasks: "/api/v1/buffet-admin/tasks",
      taskById: (id: string) => `/api/v1/buffet-admin/tasks/${id}`,
      assignTask: (id: string) => `/api/v1/buffet-admin/tasks/${id}/assign`,
      taskStatus: (id: string) => `/api/v1/buffet-admin/tasks/${id}/status`,
      locations: "/api/v1/buffet-admin/locations",
      staff: "/api/v1/buffet-admin/staff",
      staffDuty: (id: string) => `/api/v1/buffet-admin/staff/${id}/duty`,
      loadSummary: "/api/v1/buffet-admin/load-summary",
    },
    valet: {
      base: "/api/v1/valet",
      drivers: "/api/v1/valet/drivers",
      driversAvailable: "/api/v1/valet/drivers/available",
      assignments: "/api/v1/valet/assignments",
      assignmentsMy: "/api/v1/valet/assignments/my",
      assignmentsToday: "/api/v1/valet/assignments/today",
      driverById: (id: string) => `/api/v1/valet/drivers/${id}`,
      assignmentById: (id: string) => `/api/v1/valet/assignments/${id}`,
      assignmentAccept: (id: string) => `/api/v1/valet/assignments/${id}/accept`,
      assignmentReject: (id: string) => `/api/v1/valet/assignments/${id}/reject`,
      assignmentStart: (id: string) => `/api/v1/valet/assignments/${id}/start`,
      assignmentComplete: (id: string) => `/api/v1/valet/assignments/${id}/complete`,
    },
    valetAdmin: {
      base: "/api/v1/valet-admin",
      tasks: "/api/v1/valet-admin/tasks",
      drivers: "/api/v1/valet-admin/drivers",
      driversLoad: "/api/v1/valet-admin/drivers/load",
      zones: "/api/v1/valet-admin/zones",
      parkingDashboard: "/api/v1/valet-admin/parking-dashboard",
      assignTask: (id: string, type: string) => `/api/v1/valet-admin/tasks/${id}/assign?type=${type}`,
    },
    valetDriver: {
      base: "/api/v1/valet-driver",
      myTasks: "/api/v1/valet-driver/my-tasks",
      taskById: (id: string) => `/api/v1/valet-driver/tasks/${id}`,
      taskStatus: (id: string) => `/api/v1/valet-driver/tasks/${id}/status`,
    },
    valetSelfService: {
      base: "/api/v1/valet/self-service",
      byId: (id: string) => `/api/v1/valet/self-service/${id}`,
    },
    notifications: "/api/v1/notifications",
    gates: {
      base: "/api/v1/gates",
      config: "/api/v1/gates/config",
      verify: "/api/v1/gates/verify",
      logs: "/api/v1/gates/logs",
      logsToday: "/api/v1/gates/logs/today",
      stats: "/api/v1/gates/stats",
    },
    security: {
      base: "/api/v1/security",
      today: "/api/v1/security/today",
      todaySummary: "/api/v1/security/today/summary",
      alerts: "/api/v1/security/alerts",
      gate: {
        scan: "/api/v1/security/gate/scan",
        checkIn: "/api/v1/security/gate/check-in",
        checkOut: "/api/v1/security/gate/check-out",
      },
      gateLogs: "/api/v1/security/gate-logs",
      visits: "/api/v1/security/visits",
    },
    reception: {
      base: "/api/v1/reception",
      today: "/api/v1/reception/today",
      todaySummary: "/api/v1/reception/today/summary",
      search: "/api/v1/reception/search",
      alerts: "/api/v1/reception/alerts",
      roomsToday: "/api/v1/reception/rooms/today",
      walkIn: "/api/v1/reception/walk-in",
      communicationOverride: "/api/v1/reception/communication-override",
      visits: "/api/v1/reception/visits",
      requests: "/api/v1/reception/requests",
    },
    admin: {
      base: "/api/v1/admin",
      analytics: {
        summary: "/api/v1/admin/analytics/summary",
        export: "/api/v1/admin/analytics/export",
        schedules: "/api/v1/admin/analytics/schedules",
        schedule: "/api/v1/admin/analytics/schedule",
      },
      notifications: {
        send: "/api/v1/admin/notifications/send",
      },
      reminderRules: "/api/v1/admin/reminder-rules",
    },
  },
};

export default apiConfig;
